CC = gcc
CPPFLAGS = 
CFLAGS = 
AR = 
ARFLAGS = 
RANLIB = 
SRCFILES = codabar.c code128.c code93.c i25.c msi.c plessey.c svg.c code11.c code39.c ean.c library.c pcl.c ps.c


all: libbarcode.a



clean: rm -f 
